### ISSUE TITLE
Full corpus hangs on frontend

### ISSUE THREAD

**Issue by tim-mccarthy** [aas-integration/integration-test2#26]
I tried running run_all.sh on pascali. The backend completed (randoop hung on imgscalr, but after killing that, the rest of the backend worked). As soon as it got to the frontend, the process hung and would not proceed, even when I tried to Ctrl-C it.

Log here: [frontend.txt](https://github.com/aas-integration/integration-test2/files/643499/frontend.txt)

It seems like there's some kind of deadlock or infinite loop in the simprog code, based on lines like:

```
KeyboardInterrupt
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/home/ttm/integration-test2/simprog/vector.py", line 14, in compute_similarity_between_vectors
    racquire()
```

**Comment by martinschaef** [comment]
@langkymus could you have a look?

**Comment by langkymus** [comment]
Already looking. It could also just be that it is taking a long time to run.

**Comment by martinschaef** [comment]
Agreed, that's a big project. But still, it should terminate. One thing that we should do is to split run_all into one part that only runs physics and one that only runs image processing. I think if you compute similarity between jmonkey and imagej, this will run forever since both are huge.

@hsanchez is working on sth that partitions the corpus into clusters that are likely to be related. Once stable, this will be used to avoid running the similarity stuff across projects that are likely to be unrelated. But for now, we can just hard-code that.

**Comment by martinschaef** [comment]
Btw., @langkymus, is the similarity currently only searching for similar methods in other projects? Because that's what we want - there is no need to look for similar methods within the same project for now.

**Comment by tim-mccarthy** [comment]
If it's running a long time, it's a **really** long time. I kicked it off again around 5pm yesterday and it has made no progress since

```
********* END OF BACKEND **********
```

**Comment by martinschaef** [comment]
End of backend is a good sign though ... at least the backend terminated and most of the stuff has been produced.

**Comment by langkymus** [comment]
It should only look for similar methods across projects now (which was the case in the old backend, not sure what happened). 

I have added a separate run_simprog.py with command-line options to check similarity for specific projects in a list of projects. I will use that to test the problem reported by Tim.

**Comment by langkymus** [comment]
@tim-mccarthy, running prog2dfg through dljc on catalano does not produce the dljc-out folder. Any idea?

**Comment by markro49** [comment]
I think that one is different and the folder is an extra level down.  Under Catalano.Image I believe.  Did you look there?

**Comment by langkymus** [comment]
Yea, I found it. The problem was actually the generated "corpus/catalano/Catalano.Image/dljc-out/dot" folder contained nothing after graph generation.

**Comment by langkymus** [comment]
@tim-mccarthy, about the hanging issue, running just "./run_one.sh Sort09" now hangs and "run_simprog.py" with just Sort07 and Sort09 finishes in a few seconds.
