### ISSUE TITLE
"python backend.py" does nothing?

### ISSUE THREAD

**Issue by mernst** [aas-integration/integration-test2#27]
I'm trying to follow the instructions in the `README.md` file.

After running `python fetch.py` (which took a long time, printed progress reports, and seemed to download the projects as desired), I ran `python backend.py`.  This completed immediately, so I suspect it didn't compile the project and generate tests and dtrace files.

**Comment by martinschaef** [comment]
That description needs to be updated. One needs to fetch the corpus first and then use one of these run_*.sh scripts to actually run the tools. And the frontend still throws an exception. Will update the readme once all fixes are committed. 

---
Martin Schäf

**Comment by mernst** [comment]
OK, please let me know when you have updated, so I can test.

**Comment by mernst** [comment]
By the way, I only need to run the backend for now, so there's no need for me to delay until all frontend issues are resolved.

**Comment by martinschaef** [comment]
In that case, run the fetch corpus script and look into run_restricted.sh - I only have a phone for the next couple of hours, so I can't edit anything.

---
Martin Schäf

**Comment by martinschaef** [comment]
Updated the readme a bit. Will add more later tonight once I've merged all the text from the other folks.
Would you mind taking a look at the bullet list of tools? If you don't like the randoop/daikon text, or if you want to add links to tools and the tutorial, feel free to edit.

**Comment by mernst** [comment]
I added links to a few tools and tutorials.  I've also been updating the list of dependencies as I have discovered ones that are not listed.
