### ISSUE TITLE
JAVA_HOME message on Mac OS

### ISSUE THREAD

**Issue by bjkeller** [aas-integration/integration-test2#30]
When running `run_mini.sh` on Mac the following message is given

>ERROR in pa2checker.recompile_checker_framework(): Gradle will fail if your JAVA_HOME environment variable is unset. Please set it and try again.

In MacOS JAVA_HOME is available via a command [/usr/libexec/java_home](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/java_home.1.html).  But, Gradle runs properly on a Mac, so, the value of JAVA_HOME should also be available as `System.properties.'java.home' within Gradle.

**Comment by tim-mccarthy** [comment]
Fixed with 6380a2e9f3042ab2dddfa7304b9b3e18847de0c1.
