### ISSUE TITLE
fetch.py does not download all necessary dependencies

### ISSUE THREAD

**Issue by XujieSi** [aas-integration/integration-test2#33]
I have followed environment setup instructions step by step,  but ./run_restricted.sh failed to run. 

With some efforts of debugging, I found at least the following two things should be setup:
(1) create directory  "tools" and download do-like-javac into it
(2) download bixie.jar into directory "libs"

Even though I still got failures, which might be caused by other missing dependencies. 

[log_run_restricted.txt](https://github.com/aas-integration/integration-test2/files/724669/log_run_restricted.txt)

**Comment by martinschaef** [comment]
Hmmm ... [fetch_dependencies.sh](https://github.com/aas-integration/integration-test2/blob/master/fetch_dependencies.sh#L20) has a line to fetch the bixie.jar ... looks like something fails earlier and stops the script.

@tim-mccarthy can you take a look? 

We probably should add a travis thingy that detects this kind of issues early.

**Comment by XujieSi** [comment]
@martinschaef thanks for pointing out fetch_dependencies.sh
I debugged it a little bit, and it seems that the error "curl cannot be found" is ignored silently.

So, the root cause should be: 
curl does not come with ubuntu 14.04 by default, we have to install it.

**Comment by martinschaef** [comment]
Wow ... I would have bet that curl is there ... I'll add that to the readme :) thanks for pointing it out. If that solves it, feel free to close the issue.
