### ISSUE TITLE
Unused branches

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/integration-test2#35]
@CharlesZ-Chen, you have a bunch of branches for which there was a pull request at some point but that are not deleted. Would you mind deleting them? They are all behind master, so they don't contain anything new.

**Comment by CharlesZ-Chen** [comment]
Sure, will delete them!
Martin <notifications@github.com>于2017年2月1日 周三16:20写道：

**Comment by CharlesZ-Chen** [comment]
@martinschaef Already deleted them.

**Comment by martinschaef** [comment]
thx

**Comment by CharlesZ-Chen** [comment]
no problem!
Martin <notifications@github.com>于2017年2月2日 周四14:02写道：
