### ISSUE TITLE
Feature request:  time limit individual sub-test rather than entire run_dljc

### ISSUE THREAD

**Issue by markro49** [aas-integration/integration-test2#38]
Having a 30 minute time limit on run_dljc is a problem for the larger suites like boofcv and jmonkeyengine.  I think it would be better to have a shorter limit on each individual sub-test.  Or at least have a way to set different limits for different suites.

**Comment by tim-mccarthy** [comment]
I will add this, hopefully next week, by moving the time limit functionality from the integration test directly into DLJC. I'll probably allow 30 minutes for any given command invoked by DLJC by default, with an option to override per-project.

**Comment by tim-mccarthy** [comment]
Done. As of 03c653f, there is now a 900 second (15 minute) time limit per DLJC-subcommand, and the overall time limit has been removed.

That time limit can be adjusted per-project by adding a "timelimit" entry for that project in corpus.json.
