### ISSUE TITLE
Exception in inference.

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/integration-test2#8]
When running the checker framework inference, we run into an exception:
```
Nov 11, 2016 7:39:16 AM checkers.inference.InferenceMain getRealChecker
SEVERE: Error instantiating checker class "ontology.OntologyChecker".
java.lang.ClassNotFoundException: ontology.OntologyChecker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
```

To reproduce, do the following steps:
```
git pull
./fetch_dependencies.sh
./run_mini.sh
python frontend_pa_inference.py 
```

**Comment by CharlesZ-Chen** [comment]
@martinschaef  Hi Martin, ontology needs some support changes made in the master branch of `do-like-javac` here:

https://github.com/SRI-CSL/do-like-javac/blob/master/do_like_javac/tools/infer.py

But now it seems the `fetch_dependencies.sh` checkout the `dljc` to branch `split-dyntrace`, which doesn't have the changes I made in `infer.py` in the master branch of dljc.

Could we merge the changes from `master` branch to `split-dyntrace` branch?

Thanks!

**Comment by tim-mccarthy** [comment]
I've merged the changes in DLJC, but I'm unable to do any testing at the moment, so someone else will have to confirm it works.

**Comment by CharlesZ-Chen** [comment]
@tim-mccarthy  Thanks a lot! I've tested the merged change in my local machine, and it works.

**Comment by martinschaef** [comment]
@CharlesZ-Chen @wmdietl looks good on my machine now. Not all inferences pass for these sorting examples. E.g.,

```
Nov 11, 2016 3:52:08 PM checkers.inference.InferenceMain$DefaultResultHandler handleCompilerResult
INFO: error: Inferred value should not be missing annotations: int
  Compilation unit: /Users/schaef/git/integration-test2/corpus/Sort10/src/Sort10.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:744)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:28)
 org.checkerframework.framework.type.DefaultInferredTypesApplier.removePrimaryTypeVarApplyUpperBound(DefaultInferredTypesApplier.java:94)
 org.checkerframework.framework.type.DefaultInferredTypesApplier.apply(DefaultInferredTypesApplier.java:72)
...
```

is this ok? Can you check if the output makes sense?

**Comment by CharlesZ-Chen** [comment]
@martinschaef  Yes, this `missing annotation` error is an exception we've fixed already. The PR of this fix is still under merging and I will propagate it to `pascaliUWat` once it get merged.

**Comment by CharlesZ-Chen** [comment]
the `missing annotation` fix has been propagated to `pascaliUWat`. Thus it should success infer on sorting examples now.
